apiVersion: v1
kind: ServiceAccount
metadata:
  name: nexus-patrol
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nexus-patrol-binding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: nexus-patrol
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
