apiVersion: v1
kind: Secret
metadata:
  name: python-patrol-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: python-patrol
type: kubernetes.io/service-account-token
